name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipe-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
     name: Baixar dependencias
    - run: echo SONAR
     name: Executando chamada do SONAR
    - run: npm run build --if-present
     name: Executando o Build
    - run: npm test
     name: Executando os testes
    - run: ls -lha
     name: Listando o diretório